DROP SCHEMA IF EXISTS encounters CASCADE;
CREATE SCHEMA encounters;
-- Potwory
CREATE TABLE encounters.potwory(
    "id" SERIAL NOT NULL ,
    "nazwa" VARCHAR(255) NOT NULL,
    "opis" VARCHAR(1000) NOT NULL,
    "poziom_trudnosci" INTEGER NOT NULL,
    "id_rasa" INTEGER NOT NULL
);
CREATE INDEX "potwory_nazwa_index" ON
    encounters.potwory("nazwa");
CREATE INDEX "potwory_poziom_trudnosci_index" ON
    encounters.potwory("poziom_trudnosci");
ALTER TABLE
    encounters.potwory ADD PRIMARY KEY("id");
-- -- Tereny
-- CREATE TABLE "tereny"(
--     "id" SERIAL INTEGER NOT NULL,
--     "nazwa" VARCHAR(255) NOT NULL,
--     "opis" VARCHAR(255) NOT NULL
-- );
-- ALTER TABLE
--     "tereny" ADD PRIMARY KEY("id");
-- -- Potyczki
-- CREATE TABLE "potyczki"(
--     "id" SERIAL INTEGER NOT NULL,
--     "tytul" VARCHAR(255) NOT NULL,
--     "opis" VARCHAR(255) NOT NULL,
--     "id_lokacja" INTEGER NOT NULL,
--     "poziom_trudnosci" INTEGER NOT NULL,
--     "id_tworca" INTEGER NOT NULL
-- );
-- CREATE INDEX "potyczki_id_tworca_index" ON
--     "potyczki"("id_tworca");
-- CREATE INDEX "potyczki_tytul_index" ON
--     "potyczki"("tytul");
-- ALTER TABLE
--     "potyczki" ADD PRIMARY KEY("id");
-- -- Skarby
-- CREATE TABLE "skarby"(
--     "id" SERIAL INTEGER NOT NULL,
--     "nazwa" INTEGER NOT NULL,
--     "opis" VARCHAR(255) NOT NULL,
--     "rzadkosc" INTEGER NOT NULL,
--     "wartosc" INTEGER NOT NULL
-- );
-- CREATE INDEX "skarby_rzadkosc_index" ON
--     "skarby"("rzadkosc");
-- CREATE INDEX "skarby_nazwa_index" ON
--     "skarby"("nazwa");
-- ALTER TABLE
--     "skarby" ADD PRIMARY KEY("id");
-- -- Rasy
-- CREATE TABLE "rasy"(
--     "id" SERIAL INTEGER NOT NULL,
--     "nazwa" VARCHAR(255) NOT NULL,
--     "opis" VARCHAR(255) NOT NULL,
--     "id_teren" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "rasy" ADD PRIMARY KEY("id");
-- -- Potwór - Potyczka
-- CREATE TABLE "potwor_potyczka"(
--     "id" SERIAL INTEGER NOT NULL,
--     "id_potyczka" INTEGER NOT NULL,
--     "id_potwor" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "potwor_potyczka" ADD PRIMARY KEY("id");
-- -- Lokacje
-- CREATE TABLE "lokacje"(
--     "id" SERIAL INTEGER NOT NULL,
--     "nazwa" INTEGER NOT NULL,
--     "opis" VARCHAR(255) NOT NULL,
--     "id_teren" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "lokacje" ADD PRIMARY KEY("id");
-- -- Skarb - Potyczka
-- CREATE TABLE "skarb_potyczka"(
--     "id" SERIAL INTEGER NOT NULL,
--     "id_potyczka" INTEGER NOT NULL,
--     "id_skarb" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "skarb_potyczka" ADD PRIMARY KEY("id");
-- -- Pułapki
-- CREATE TABLE "pułapki"(
--     "id" SERIAL INTEGER NOT NULL,
--     "nazwa" VARCHAR(255) NOT NULL,
--     "opis" VARCHAR(255) NOT NULL,
--     "poziom_trudnosci" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "pułapki" ADD PRIMARY KEY("id");
-- -- Pułapka - Potyczka
-- CREATE TABLE "pułapka_potyczka"(
--     "id" SERIAL INTEGER NOT NULL,
--     "id_potyczka" INTEGER NOT NULL,
--     "id_pułapka" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "pułapka_potyczka" ADD PRIMARY KEY("id");
-- -- Osoby
-- CREATE TABLE "osoby"(
--     "id" SERIAL INTEGER NOT NULL,
--     "nazwa" VARCHAR(255) NOT NULL,
--     "login" VARCHAR(255) NOT NULL,
--     "haslo" VARCHAR(255) NOT NULL
-- );
-- CREATE INDEX "osoby_nazwa_index" ON
--     "osoby"("nazwa");
-- CREATE INDEX "osoby_login_index" ON
--     "osoby"("login");
-- ALTER TABLE
--     "osoby" ADD PRIMARY KEY("id");
-- -- Rasa - Teren
-- CREATE TABLE "rasa_teren"(
--     "id" SERIAL INTEGER NOT NULL,
--     "id_rasa" INTEGER NOT NULL,
--     "id_teren" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "rasa_teren" ADD PRIMARY KEY("id");
-- -- Uprawnienia
-- CREATE TABLE "uprawnienia"(
--     "id" SERIAL INTEGER NOT NULL,
--     "nazwa" VARCHAR(255) NOT NULL,
--     "typ" VARCHAR(255) NOT NULL
-- );
-- CREATE INDEX "uprawnienia_typ_index" ON
--     "uprawnienia"("typ");
-- ALTER TABLE
--     "uprawnienia" ADD PRIMARY KEY("id");
-- -- Uprawnienia - Osoby
-- CREATE TABLE "uprawnienia_osoby"(
--     "id" SERIAL INTEGER NOT NULL,
--     "id_uprawniennie" INTEGER NOT NULL,
--     "id_osoba" INTEGER NOT NULL
-- );
-- ALTER TABLE
--     "uprawnienia_osoby" ADD PRIMARY KEY("id");
-- ALTER TABLE
--     "potwory" ADD CONSTRAINT "potwory_id_rasa_foreign" FOREIGN KEY("id_rasa") REFERENCES "rasy"("id");
-- ALTER TABLE
--     "potwor_potyczka" ADD CONSTRAINT "potwor_potyczka_id_potyczka_foreign" FOREIGN KEY("id_potyczka") REFERENCES "potyczki"("id");
-- ALTER TABLE
--     "skarb_potyczka" ADD CONSTRAINT "skarb_potyczka_id_potyczka_foreign" FOREIGN KEY("id_potyczka") REFERENCES "potyczki"("id");
-- ALTER TABLE
--     "pułapka_potyczka" ADD CONSTRAINT "pułapka_potyczka_id_potyczka_foreign" FOREIGN KEY("id_potyczka") REFERENCES "potyczki"("id");
-- ALTER TABLE
--     "potyczki" ADD CONSTRAINT "potyczki_id_lokacja_foreign" FOREIGN KEY("id_lokacja") REFERENCES "lokacje"("id");
-- ALTER TABLE
--     "skarb_potyczka" ADD CONSTRAINT "skarb_potyczka_id_skarb_foreign" FOREIGN KEY("id_skarb") REFERENCES "skarby"("id");
-- ALTER TABLE
--     "potwor_potyczka" ADD CONSTRAINT "potwor_potyczka_id_potwor_foreign" FOREIGN KEY("id_potwor") REFERENCES "potwory"("id");
-- ALTER TABLE
--     "lokacje" ADD CONSTRAINT "lokacje_id_teren_foreign" FOREIGN KEY("id_teren") REFERENCES "tereny"("id");
-- ALTER TABLE
--     "pułapka_potyczka" ADD CONSTRAINT "pułapka_potyczka_id_pułapka_foreign" FOREIGN KEY("id_pułapka") REFERENCES "pułapki"("id");
-- ALTER TABLE
--     "potyczki" ADD CONSTRAINT "potyczki_id_tworca_foreign" FOREIGN KEY("id_tworca") REFERENCES "osoby"("id");
-- ALTER TABLE
--     "uprawnienia_osoby" ADD CONSTRAINT "uprawnienia_osoby_id_uprawniennie_foreign" FOREIGN KEY("id_uprawniennie") REFERENCES "uprawnienia"("id");
-- ALTER TABLE
--     "uprawnienia_osoby" ADD CONSTRAINT "uprawnienia_osoby_id_osoba_foreign" FOREIGN KEY("id_osoba") REFERENCES "osoby"("id");
-- ALTER TABLE
--     "rasa_teren" ADD CONSTRAINT "rasa_teren_id_rasa_foreign" FOREIGN KEY("id_rasa") REFERENCES "rasy"("id");
-- ALTER TABLE
--     "rasa_teren" ADD CONSTRAINT "rasa_teren_id_teren_foreign" FOREIGN KEY("id_teren") REFERENCES "tereny"("id");